protein_core_home:
    path:     /
    defaults: { _controller: ProteinCoreBundle:Landing:landing }



protein_core_requests_subpage:
    path:     /requests/{_subpage}
    defaults: { _controller: ProteinCoreBundle:Landing:requests }
    requirements:
        _subpage: \d+

protein_core_requests:
    path:     /requests/
    defaults: { _controller: ProteinCoreBundle:Landing:requests }


protein_core_species_subpage:
    path:     /species/{_subpage}
    defaults: { _controller: ProteinCoreBundle:Landing:species }
    requirements:
        _subpage: \d+

protein_core_species:
    path:     /species/
    defaults: { _controller: ProteinCoreBundle:Landing:species }


protein_core_protein_subpage:
    path:     /protein/{_subpage}
    defaults: { _controller: ProteinCoreBundle:Landing:protein }
    requirements:
        _subpage: \d+

protein_core_protein:
    path:     /protein/
    defaults: { _controller: ProteinCoreBundle:Landing:protein }


protein_core_index_global_subpage:
    path:     /global_index/{_subpage}
    defaults: { _controller: ProteinCoreBundle:Landing:indexglobal }
    requirements:
        _subpage: \d+

protein_core_index_global:
    path:     /global_index/
    defaults: { _controller: ProteinCoreBundle:Landing:indexglobal }

protein_core_page_index_file:
    path:     /{pageslug}/index
    defaults: { _controller: ProteinCoreBundle:Landing:index }
    requirements:
        pageslug: \w+

protein_core_index_file:
    path:     /index
    defaults: { _controller: ProteinCoreBundle:Landing:index }

protein_core_page_calculate:
    path:     /{pageslug}/calculate
    defaults: { _controller: ProteinCoreBundle:Landing:calculate }
    requirements:
        pageslug: \w+

protein_core_calculate:
    path:     /calculate
    defaults: { _controller: ProteinCoreBundle:Landing:calculate }

protein_core_swiss_file:
    path:     /swiss
    defaults: { _controller: ProteinCoreBundle:Landing:swiss }

protein_core_page_swiss_file:
    path:     /{pageslug}/swiss
    defaults: { _controller: ProteinCoreBundle:Landing:swiss }
    requirements:
        pageslug: \w+

protein_core_fasta_file:
    path:     /fasta
    defaults: { _controller: ProteinCoreBundle:Landing:fasta }

protein_core_page_fasta_file:
    path:     /{pageslug}/fasta
    defaults: { _controller: ProteinCoreBundle:Landing:fasta }
    requirements:
        pageslug: \w+

protein_core_aminotable:
    path:     /{pageslug}/aminotable/
    defaults: { _controller: ProteinCoreBundle:Landing:aminotable }
    requirements:
        pageslug: \w+

protein_core_aminotable_subpage:
    path:     /{pageslug}/aminotable/{_subpage}
    defaults: { _controller: ProteinCoreBundle:Landing:aminotable }
    requirements:
        pageslug: \w+
        _subpage: \d+

protein_core_page_amino_file:
    path:     /{pageslug}/amino
    defaults: { _controller: ProteinCoreBundle:Landing:amino }
    requirements:
        pageslug: \w+

protein_core_amino_file:
    path:     /amino
    defaults: { _controller: ProteinCoreBundle:Landing:amino }

protein_core_page_pdb_file:
    path:     /{pageslug}/pdbfile
    defaults: { _controller: ProteinCoreBundle:Landing:pdbfile }
    requirements:
        pageslug: \w+

protein_core_pdb_file:
    path:     /pdbfile
    defaults: { _controller: ProteinCoreBundle:Landing:pdbfile }

protein_core_api:
    path:     /api
    defaults: { _controller: ProteinCoreBundle:Api:index }

protein_core_api_init:
    path:     /api/init
    defaults: { _controller: ProteinCoreBundle:Api:default }

protein_core_about:
    path:     /about
    defaults: { _controller: ProteinCoreBundle:Static:about }

protein_core_page:
    path:     /{pageslug}/
    defaults: { _controller: ProteinCoreBundle:Landing:landing }
    requirements:
        pageslug: \w+

protein_core_page_subpage:
    path:     /{pageslug}/{_subpage}
    defaults: { _controller: ProteinCoreBundle:Landing:landing }
    requirements:
        pageslug: \w+
        _subpage: \d+

