<?php

namespace Protein\CoreBundle\Entity;

/**
 * IndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexRepository extends \Doctrine\ORM\EntityRepository
{
}
