<?php

namespace Protein\CoreBundle\Entity;

/**
 * ModelRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
