<?php

namespace Protein\CoreBundle\Entity;

/**
 * ProteinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProteinRepository extends \Doctrine\ORM\EntityRepository
{
}
